In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("agentina.csv")
df1 = pd.read_csv("australia.csv")
df2 = pd.read_csv("costa rica.csv")
df3 = pd.read_csv("denmark.csv")
df4 = pd.read_csv("england.csv")
df5 = pd.read_csv("france.csv")
df6 = pd.read_csv("iran.csv")
df7 = pd.read_csv("maxico.csv")
df8 = pd.read_csv("netherlands.csv")
df9 = pd.read_csv("poland.csv")
df10 = pd.read_csv("saudi arabia.csv")
df11 = pd.read_csv("senegal.csv")
df12 = pd.read_csv("spain.csv")
df13 = pd.read_csv("tunisia.csv")
df14 = pd.read_csv("usa.csv")
df15 = pd.read_csv("wales.csv")

In [24]:
df.columns

Index(['Date', 'Day', 'Comp', 'Round', 'Venue', 'Result', 'Squad', 'Opponent',
       'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh', 'SoT', 'CrdY',
       'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG', 'xAG', 'SCA',
       'GCA', 'Cmp', 'Att', 'Cmp%', 'Prog', 'Succ', 'Att.1', 'Match Report',
       'Fls', 'Fld', 'Off', 'Crs', 'TklW', 'OG', 'PKwon', 'PKcon',
       'Defensive Tkl', 'Defensive TklW', 'Defensive Att', 'Defensive Tkl%',
       'Defensive Past', 'Defensive Blocks', 'Defensive Sh', 'Defensive Pass',
       'Defensive Int', 'Defensive Tkl+Int', 'Defensive Clr', 'Defensive Err'],
      dtype='object')

In [25]:
frames = [df,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15]

In [26]:
data=pd.concat(frames)

In [27]:
data.to_csv("worldcupdata.csv",index=False)

In [28]:
data = pd.read_csv("worldcupdata.csv")

In [29]:
data

,Date,Day,Comp,Round,Venue,Result,Squad,Opponent,Start,Pos,...,Defensive Att,Defensive Tkl%,Defensive Past,Defensive Blocks,Defensive Sh,Defensive Pass,Defensive Int,Defensive Tkl+Int,Defensive Clr,Defensive Err
0,23-03-2018,Fri,Friendlies (M),Friendlies (M),Home,W 2–0,ar Argentina,it Italy,Y,AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,23-03-2018,Fri,Friendlies (M),Friendlies (M),Home,W 2–0,ar Argentina,it Italy,N,"On matchday squad, but did not play",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,23-03-2018,Fri,Friendlies (M),Friendlies (M),Home,W 2–0,ar Argentina,it Italy,N,"On matchday squad, but did not play",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23-03-2018,Fri,Friendlies (M),Friendlies (M),Home,W 2–0,ar Argentina,it Italy,N,"On matchday squad, but did not play",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23-03-2018,Fri,Friendlies (M),Friendlies (M),Home,W 2–0,ar Argentina,it Italy,Y,DM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12250,21-11-2022,Mon,World Cup,Group stage,Neutral,D 1–1,wls Wales,us United States,N,"On matchday squad, but did not play",...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12251,21-11-2022,Mon,World Cup,Group stage,Neutral,D 1–1,wls Wales,us United States,Y,CM,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12252,21-11-2022,Mon,World Cup,Group stage,Neutral,D 1–1,wls Wales,us United States,Y,FW,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12253,21-11-2022,Mon,World Cup,Group stage,Neutral,D 1–1,wls Wales,us United States,Y*,"FW,LW",...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12254,21-11-2022,Mon,World Cup,Group stage,Neutral,D 1–1,wls Wales,us United States,Y,GK,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [21]:
result = pd.concat(frames,ignore_index=True)

In [22]:
df = result.copy()

In [23]:
df

,Date,Day,Comp,Round,Venue,Result,Squad,Opponent,Start,Pos,...,Att.1,Match Report,Fls,Fld,Off,Crs,TklW,OG,PKwon,PKcon
0,11-11-2016,Fri,WCQ,First round,Home,W 2–1,fr France,se Sweden,N,"On matchday squad, but did not play",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15-11-2016,Tue,Friendlies (M),Friendlies (M),Home,D 0–0,fr France,ci Côte d'Ivoire,Y,CM,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25-03-2017,Sat,WCQ,First round,Away,W 3–1,fr France,lu Luxembourg,N,NaN,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28-03-2017,Tue,Friendlies (M),Friendlies (M),Home,L 0–2,fr France,es Spain,Y,CM,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02-06-2017,Fri,Friendlies (M),Friendlies (M),Home,W 5–0,fr France,py Paraguay,N,"On matchday squad, but did not play",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1199,22-09-2022,Thu,UEFA Nations League,League A,Home,W 2–0,fr France,at Austria,Y,DM,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1200,25-09-2022,Sun,UEFA Nations League,League A,Away,L 0–2,fr France,dk Denmark,N,NaN,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1201,22-11-2022,Tue,World Cup,Group stage,Neutral,W 4–1,fr France,au Australia,N,DM,...,0.0,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.columns

Index(['Date', 'Day', 'Comp', 'Round', 'Venue', 'Result', 'Squad', 'Opponent',
       'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh', 'SoT', 'CrdY',
       'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG', 'xAG', 'SCA',
       'GCA', 'Cmp', 'Att', 'Cmp%', 'Prog', 'Succ', 'Att.1', 'Match Report',
       'Fls', 'Fld', 'Off', 'Crs', 'TklW', 'OG', 'PKwon', 'PKcon'],
      dtype='object')