In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("Adrien Rabiot.csv")
df1 = pd.read_csv("Adrien Truffert.csv")
df2 = pd.read_csv("Alphonse Areola.csv")
df3 = pd.read_csv("Antoine Griezmann.csv")
df4 = pd.read_csv("Aurelien Tchouameni.csv")
df5 = pd.read_csv("Benjamin Pavard.csv")
df6 = pd.read_csv("Benoit Badiashile Mukinayi.csv")
df7 = pd.read_csv("Christopher Nkunku.csv")
df8 = pd.read_csv("Dayotchanculle Upamecano.csv")
df9 = pd.read_csv("Eduardo Camavinga.csv")
df10 = pd.read_csv("Ferland Mendy.csv")
df11 = pd.read_csv("Hugo Lloris.csv")
df12 = pd.read_csv("Ibrahima Konate.csv")
df13 = pd.read_csv("Jonathan Clauss.csv")
df14 = pd.read_csv("Jordan Veretout.csv")
df15 = pd.read_csv("Jules Kounde.csv")
df16 = pd.read_csv("Kingsley Coman.csv")
df17 = pd.read_csv("Kylian Mbappe.csv")
df18 = pd.read_csv("Lucas Hernandez.csv")
df19 = pd.read_csv("Marcus Thuram.csv")
df20 = pd.read_csv("Matteo Guendouzi.csv")
df21 = pd.read_csv("Olivier Giroud.csv")
df22 = pd.read_csv("Ousmane Dembele.csv")
df23 = pd.read_csv("Randal Kolo Muani.csv")
df24 = pd.read_csv("Raphael Varane.csv")
df25 = pd.read_csv("Steve Mandanda.csv")
df26 = pd.read_csv("Theo Hernandez.csv")
df27 = pd.read_csv("William Saliba.csv")
df28 = pd.read_csv("Youssouf Fofana.csv")

In [20]:
frames = [df,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,df23,df24,df25,df26,df27,df28]

In [21]:
result = pd.concat(frames,ignore_index=True)

In [22]:
df = result.copy()

In [23]:
df

,Date,Day,Comp,Round,Venue,Result,Squad,Opponent,Start,Pos,...,Att.1,Match Report,Fls,Fld,Off,Crs,TklW,OG,PKwon,PKcon
0,11-11-2016,Fri,WCQ,First round,Home,W 2–1,fr France,se Sweden,N,"On matchday squad, but did not play",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15-11-2016,Tue,Friendlies (M),Friendlies (M),Home,D 0–0,fr France,ci Côte d'Ivoire,Y,CM,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25-03-2017,Sat,WCQ,First round,Away,W 3–1,fr France,lu Luxembourg,N,NaN,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28-03-2017,Tue,Friendlies (M),Friendlies (M),Home,L 0–2,fr France,es Spain,Y,CM,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02-06-2017,Fri,Friendlies (M),Friendlies (M),Home,W 5–0,fr France,py Paraguay,N,"On matchday squad, but did not play",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1199,22-09-2022,Thu,UEFA Nations League,League A,Home,W 2–0,fr France,at Austria,Y,DM,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1200,25-09-2022,Sun,UEFA Nations League,League A,Away,L 0–2,fr France,dk Denmark,N,NaN,...,NaN,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1201,22-11-2022,Tue,World Cup,Group stage,Neutral,W 4–1,fr France,au Australia,N,DM,...,0.0,Match Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.columns

Index(['Date', 'Day', 'Comp', 'Round', 'Venue', 'Result', 'Squad', 'Opponent',
       'Start', 'Pos', 'Min', 'Gls', 'Ast', 'PK', 'PKatt', 'Sh', 'SoT', 'CrdY',
       'CrdR', 'Touches', 'Tkl', 'Int', 'Blocks', 'xG', 'npxG', 'xAG', 'SCA',
       'GCA', 'Cmp', 'Att', 'Cmp%', 'Prog', 'Succ', 'Att.1', 'Match Report',
       'Fls', 'Fld', 'Off', 'Crs', 'TklW', 'OG', 'PKwon', 'PKcon'],
      dtype='object')

In [25]:
df.to_csv("france_sum_cleaned.csv",index=False)